### ISSUE TITLE
How to handle starting the section numering at 0?

### ISSUE THREAD

**Issue by Sinthoras7** [jbirnick/typst-rich-counters#3]
This package just inherits the section counter.  

But because a counter in Typst can not be set to -1, the common practice to start the section numbering from 0 is to use something like  this ([source]).
```
#set heading(
  numbering: (fst, ..nums) => numbly("Top {1}:", "{1}.{2}.")(fst - 1, ..nums),
) 
``` 
[source]: https://forum.typst.app/t/what-is-the-best-practice-for-setting-the-enum-numbering-for-every-level-individually/1107/3

So the section counter is 1 higher than the section counter that is displayed in the sections. If I now use this package (e.g. together with great theorems) this leads to something like the following:
![image](https://github.com/user-attachments/assets/dbf06e8b-1802-45f5-85c0-d69b91006e0f)
Note that it should be `Notation 0.1`, not `Notation 1.1`.

Is there a way to circumvent the problem? 
Would it be feasible to implement it in the package , such that e.g. the user can also define an offset to the counter that gets subtracted evertime the counter is used. (Or would it make more sense to implement it in the theorem package?)

**Comment by jbirnick** [comment]
Right. The problem is that the counter itself still has the `1` in the top value, only your `numbering` function displays something else. The `mathblock` or `rich-counter` can't really see the numbering function (or at least it would be bad practice to look at it), hence it doesn't know anything of the numbering change.

But you can pass a custom numbering to great-theorems as well! So you can just give great-theorems your custom numbering. Here is a full example:

```typ
#import "@preview/great-theorems:0.1.1": *
#import "@preview/rich-counters:0.2.1": *
#import "@preview/numbly:0.1.0": *

#show: great-theorems-init

#let mathcounter = rich-counter(
  identifier: "math",
  inherited_levels: 1,
)

#let notation = mathblock(
  blocktitle: "Notation",
  counter: mathcounter,
  numbering: (fst, ..nums) => numbly("Top {1}:", "{1}.{2}")(fst - 1, ..nums),
)

#set heading(
  numbering: (fst, ..nums) => numbly("Top {1}:", "{1}.{2}")(fst - 1, ..nums),
)

= Notationen

#notation[
  Test
]
```

**Comment by Sinthoras7** [comment]
Okay, thanks! I thought more about a boolean variable that can be set globally to do this for all counters or all instances of this counter, but I don't know enough of the inner workings to see, whether this is feasible and it is not really necessary to have it, because your solution works. But it would make it a little bit nicer, so if it is feasible, you know have the idea and can decide whether you want to implement it or not.

Thank you for creating the package :)

**Comment by jbirnick** [comment]
Yeah indeed that would be cool, but it is impossible at the moment. Right now, Typst separates `counter` from `numbering`s.

A counter can just count; you can step it and you can get from it the current number, or rather, a whole list of numbers, given that a counter can keep track of multiple levels.

But all the elements that _display_ a counter (`heading`, `figure`, `enum`, `rich-counter`, etc.) have a separate `numbering` field, which determines the _style_ of how the number of the counter is written. For example, for headings you might want something like `1.1`, but for enums you maybe want `a)`. For example, you will find that when you use figures, you will also have to set your custom numbering for them.

And these are native elements, so that's really how it is supposed to work for now. In my personal opinion, I would also prefer if the `numbering` "style" of the counter would be attached to the actual counter, because you would usually not display the _same_ counter in two different styles.
